function [fitresult, gof] = createFit(CdfX_G, CdfY_G)
%CREATEFIT(CDFX_G,CDFY_G)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : CdfX_G
%      Y Output: CdfY_G
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jan-2019 14:31:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( CdfX_G, CdfY_G );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.353716802637917 -0.585114140025626];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'CdfY_G vs. CdfX_G', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel CdfX_G
ylabel CdfY_G
grid on


